name: documentation

on:
    push:
        branches:
            - main
        paths:
            - docs
    workflow_dispatch:


permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: pip install -r docs/requirements.txt
      - name: Sphinx build
        run: sphinx-build docs/source _build
      - name: Upload page artifact
        uses: actions/upload-artifact@v4
        with:
          name: meca-desktop-docs-artifact
          path: docs/_build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
